### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by VitalRus95** [MatiDragon-YT/help-system#2]
There's a small mistake I noticed in the Russian translation of the help. In SCM Documentation\San Andreas\Actor IDs the last column is named «Секс», which is wrong in this particular context (a well-known ‘translator's false friend’), it should be «Пол» instead.

Anyway, thank you for the great work on the help files!

![изображение](https://user-images.githubusercontent.com/73489604/183266416-ab25c747-1a06-4a1f-bf9e-e8e68cab4d59.png)

**Comment by x87** [comment]
Second that, please correct to Пол

**Comment by MatiDragon-YT** [comment]
Thank you very much, here I already corrected them
https://github.com/MatiDragon-YT/help-system/releases/tag/1.16
